apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-frontend-service
  labels:
    app: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
