apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
