apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-backend-service
  labels:
    app: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
